In [1]:
from evaluate import Evaluator,EvaluatedDocument
from pathlib import Path
import pandas as pd 
from datetime import datetime
from collections import defaultdict
from rapidfuzz import fuzz

# Multi Evaluation

In [9]:

data = []
for experiment in (Path.cwd() / "experiments/FINAL").glob("*"):
    #print(experiment.stem)
    try:
        data.append(
            Evaluator(experiment,overwrite_training="experiments/FINAL/test.yaml").evaluate_metrics() | 
            {"Experiment":experiment.parts[-1],"Date":experiment.stat().st_ctime}
        )
    except ValueError as e:
        print(e)
        
overall = pd.DataFrame(columns=["Date","Experiment",'precision', 'recall', 'f1', 'tp', 'fp', 'fn',"fuzzy_rate","smaller","fuzzy","token_p","token_r"],data=data)
overall[['precision', 'recall', 'f1',"fuzzy_rate","token_p","token_r"]] = overall[['precision', 'recall', 'f1', "fuzzy_rate","token_p","token_r"]].map(lambda x:round(x*100,2))
overall[['tp', 'fp', 'fn']] = overall[['tp', 'fp', 'fn']].astype(int)
overall['Date'] = pd.to_datetime(overall['Date'], unit='s')
overall.sort_values("Date")#[["Experiment","fp",'precision',"fn",'recall','f1',"fuzzy_rate","token_p","token_r"]].to_latex((Path.cwd() / "resources" / "results.latex").open("w"),index=False,caption="empty",float_format="%.1f",bold_rows=True)

/workspaces/github-best-pratices/extraction/experiments/FINAL/test.yaml/outputs/result-test.jsonl does not exist

,Date,Experiment,precision,recall,f1,tp,fp,fn,fuzzy_rate,smaller,fuzzy,token_p,token_r
4,2026-04-24 03:10:25.146724224,pro-low-base,39.58,95.0,55.88,19,29,1,4.17,0,2,86.31,94.99
25,2026-04-24 03:10:36.338483810,flash-light-min-base,18.89,85.0,30.91,17,73,3,12.22,0,11,87.03,82.17
10,2026-04-24 03:11:19.456327438,flash-min-base,17.31,90.0,29.03,18,86,2,9.62,0,10,79.05,88.51
16,2026-04-24 03:28:58.829105377,pro-high-base,33.33,95.0,49.35,19,38,1,8.77,0,5,81.84,92.05
18,2026-04-24 03:57:42.190498829,pro-low-base-persona-requirements,46.34,95.0,62.30,19,22,1,4.88,0,2,88.75,83.26
7,2026-04-24 04:15:24.899390221,pro-low-base-persona-prescriptive-edge,60.00,90.0,72.00,18,12,2,6.67,0,2,87.13,79.56
6,2026-04-24 04:18:52.508560181,pro-low-base-persona-requirements-edge,56.67,85.0,68.00,17,13,3,6.67,0,2,91.33,84.59
22,2026-04-24 04:46:02.881021738,pro-low-base-persona-requirements-edge-securit...,45.00,90.0,60.00,18,22,2,2.50,0,1,87.75,78.18
14,2026-04-24 05:04:37.974025488,pro-low-base-persona-requirements-edge-securit...,69.23,90.0,78.26,18,8,2,7.69,0,2,93.13,89.91
23,2026-04-24 16:58:11.296631336,pro-low-base-persona-requirements-edge-securit...,53.33,80.0,64.00,16,14,4,10.00,0,3,86.95,89.55
9,2026-04-24 16:58:15.129634856,pro-low-base-persona-requirements-edge-securit...,48.48,80.0,60.38,16,17,4,6.06,0,2,91.07,88.82
24,2026-04-24 17:09:11.143247366,pro-low-base-persona-requirements-edge-securit...,50.00,90.0,64.29,18,18,2,11.11,0,4,87.42,84.80
2,2026-04-24 17:24:43.222238064,pro-low-base-persona-requirements-edge-securit...,54.55,90.0,67.92,18,15,2,6.06,0,2,90.34,87.52
15,2026-04-24 17:26:35.809349298,pro-low-base-persona-requirements-edge-securit...,54.55,90.0,67.92,18,15,2,6.06,0,2,92.82,87.52
27,2026-04-24 17:50:40.176750898,pro-low-base-persona-requirements-edge-securit...,34.00,85.0,48.57,17,33,3,4.00,0,2,95.96,88.14
11,2026-04-24 17:55:29.051029682,pro-low-base-persona-requirements-edge-securit...,50.00,85.0,62.96,17,17,3,5.88,0,2,96.00,84.69
17,2026-04-24 18:27:35.450723648,pro-low-base-persona-requirements-edge-securit...,52.78,95.0,67.86,19,17,1,2.78,0,1,89.08,83.11
8,2026-04-24 21:02:37.611542940,pro-low-base-pre-f_other,35.29,90.0,50.70,18,33,2,7.84,0,4,86.37,87.75
20,2026-04-24 21:03:44.588606596,pro-low-base-pre-f_med,51.52,85.0,64.15,17,16,3,12.12,0,4,86.24,86.79
3,2026-04-24 21:03:50.057611704,pro-low-base-pre-f_full,39.13,90.0,54.55,18,28,2,4.35,0,2,83.35,86.75
5,2026-04-24 21:03:55.245616674,pro-low-base-pre-f_empty,64.00,80.0,71.11,16,9,4,12.00,0,3,90.12,89.15
26,2026-05-14 01:51:49.359399080,pro-low-base-persona-prescriptive,43.90,90.0,59.02,18,23,2,2.44,0,1,87.52,89.59
0,2026-05-14 01:51:56.137403727,pro-low-base-persona,43.18,95.0,59.37,19,25,1,2.27,0,1,87.80,85.52
13,2026-05-14 03:16:03.959621429,pro-low-base-persona-requirements-edge-securit...,62.50,75.0,68.18,15,9,5,8.33,0,2,93.14,81.89
19,2026-05-14 03:22:36.545933485,pro-low-base-persona-requirements-edge-securit...,61.54,80.0,69.57,16,10,4,3.85,0,1,91.16,83.85
21,2026-05-14 21:32:28.396014214,pro-low-base-persona-requirements-edge-securit...,65.38,85.0,73.91,17,9,3,3.85,0,1,91.98,78.36
1,2026-05-14 21:32:35.995021105,pro-low-base-persona-requirements-edge-securit...,55.17,80.0,65.31,16,13,4,6.90,0,2,89.00,83.47
12,2026-05-15 01:41:27.381998301,pro-low-base-persona-requirements-edge-securit...,55.17,80.0,65.31,16,13,4,3.45,0,1,93.61,81.17
28,2026-05-15 01:41:32.979005098,pro-low-base-persona-requirements-edge-securit...,55.56,75.0,63.83,15,12,5,3.70,0,1,91.27,83.01

In [7]:
Evaluator.results_to_yaml("/workspaces/github-best-pratices/extraction/experiments/validation/baseline/outputs/result-validation.jsonl")

# Single Evaluation

In [10]:
e1 = Evaluator(
    Path.cwd() / "experiments" / "FINAL/pro-low-base-persona-requirements-edge-security-focus2".strip(),
)
df = e1.evaluate_items()
df

,File,Reference,Prediction,MultiMatch,Size,Fuzzy,Smaller,Subspan,Superspan,Exact,Partial,Disjoint (FP),Duplicate Match (FP),FP,FN,TP,IoU,token_p,token_r
0,code-security/reference/code-scanning/codeql/c...,0,0,False,2985,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
1,actions/how-tos/write-workflows/choose-what-wo...,0,1,False,148,0,0,0,0,0,0,1,0,1,0,0,0.000000,<NA>,<NA>
2,code-security/reference/code-scanning/codeql/c...,0,0,False,228,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
3,code-security/responsible-use/responsible-use-...,2,4,False,2015,0,0,0,0,2,0,2,0,2,0,2,1.000000,1.0,1.0
4,code-security/concepts/secret-security/about-b...,2,2,False,409,0,0,0,0,2,0,0,0,0,0,2,1.000000,1.0,1.0
5,code-security/how-tos/report-and-fix-vulnerabi...,0,0,False,1114,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
6,code-security/reference/code-scanning/codeql/c...,0,0,False,396,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
7,actions/how-tos/administer/view-metrics.md,0,0,False,1263,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
8,code-security/concepts/code-scanning/codeql/co...,0,0,False,419,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
9,code-security/how-tos/secure-your-secrets/cust...,0,0,False,1210,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
10,code-security/how-tos/secure-your-supply-chain...,1,2,False,444,0,0,0,1,0,0,1,0,1,0,1,0.343653,1.0,0.316667
11,actions/how-tos/secure-your-work/use-artifact-...,2,1,False,953,0,0,0,0,1,0,0,0,0,1,1,0.500000,1.0,1.0
12,code-security/tutorials/trialing-github-advanc...,0,0,False,527,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
13,code-security/how-tos/secure-your-supply-chain...,1,0,False,3374,0,0,0,0,0,0,0,0,0,1,0,0.000000,<NA>,<NA>
14,code-security/tutorials/trialing-github-advanc...,0,0,False,3017,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
15,actions/concepts/workflows-and-actions/workflo...,0,0,False,458,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
16,code-security/how-tos/report-and-fix-vulnerabi...,2,2,False,1134,1,0,0,1,0,0,1,0,1,1,1,0.473244,1.0,0.915254
17,actions/how-tos/deploy/deploy-to-third-party-p...,2,2,False,497,0,0,1,0,1,0,0,0,0,0,2,0.893541,0.860825,1.0
18,code-security/reference/code-scanning/codeql/c...,0,0,False,1252,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
19,code-security/how-tos/secure-your-secrets/mana...,0,0,False,1040,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
20,packages/managing-github-packages-using-github...,5,5,False,3143,1,0,0,3,2,0,0,0,0,0,5,0.904054,0.998837,0.898707
21,code-security/how-tos/secure-at-scale/configur...,2,2,False,905,0,0,0,1,1,0,0,0,0,0,2,0.978114,1.0,0.947917
22,code-security/how-tos/view-and-interpret-data/...,0,0,False,860,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
23,code-security/concepts/secret-security/about-d...,0,0,False,256,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
24,actions/how-tos/manage-runners/self-hosted-run...,0,0,False,938,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
25,code-security/how-tos/secure-your-secrets/cust...,1,0,False,289,0,0,0,0,0,0,0,0,0,1,0,0.000000,<NA>,<NA>
26,actions/tutorials/migrate-to-github-actions/ma...,0,0,False,1174,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
27,code-security/how-tos/manage-security-alerts/r...,0,0,False,1470,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
28,actions/concepts/workflows-and-actions/concurr...,0,0,False,141,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
29,actions/tutorials/manage-your-work/schedule-is...,0,0,False,585,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
30,code-security/how-tos/secure-your-secrets/work...,0,0,False,928,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
31,code-security/reference/supply-chain-security/...,1,0,False,2802,0,0,0,0,0,0,0,0,0,1,0,0.000000,<NA>,<NA>
32,code-security/tutorials/customize-code-scannin...,0,0,False,986,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
33,code-security/tutorials/fix-reported-vulnerabi...,1,1,False,1835,0,0,0,1,0,0,0,0,0,0,1,0.568592,1.0,0.514019
34,code-security/concepts/code-scanning/codeql/qu...,0,0,False,313,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
35,code-security/how-tos/scan-code-for-vulnerabil...,0,0,False,1635,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
36,code-security/concepts/vulnerability-reporting...,0,0,False,844,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
37,code-security/tutorials/adopting-github-advanc...,2,2,False,295,0,0,2,0,0,0,0,0,0,0,2,0.514309,0.523352,1.0
38,code-security/how-tos/secure-your-supply-chain...,0,2,False,2752,0,0,0,0,0,0,2,0,2,0,0,0.000000,<NA>,<NA>
39,code-security/how-tos/report-and-fix-vulnerabi...,0,0,False,364,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>
40,actions/how-tos/create-and-publish-actions/pub...,0,0,False,856,0,0,0,0,0,0,0,0,0,0,0,0.000000,<NA>,<NA>

In [ ]:
e1.export_annotations()

# Fuzzy

In [11]:
e1 = Evaluator(
    Path.cwd() / "experiments" / "FINAL/pro-low-base-persona-requirements-edge-security-focus2".strip(),stage="all"
)
e1.fuzzy_pairs()

ValueError: /workspaces/github-best-pratices/extraction/experiments/FINAL/pro-low-base-persona-requirements-edge-security-focus2/all.yaml does not exist

# Double Evaluation

In [9]:
e1 = Evaluator(
    Path.cwd() / "experiments" / "FINAL/pro-low-base-persona-requirements-edge-security-focus2.reps".strip(),overwrite_training="experiments/FINAL/test.yaml"
)
e2 = Evaluator(
    Path.cwd() / "experiments" / "FINAL/pro-low-base-persona-requirements-edge-security-focus2.2".strip(),overwrite_training="experiments/FINAL/test.yaml"
)

df1 = e1.evaluate_items()
df2 = e2.evaluate_items()
df1["File"] = [f"{i}. " for i in range(len(df1))] + df1["File"].str.split("/").str[-1]
df2["File"] = [f"{i}. " for i in range(len(df2))] + df2["File"].str.split("/").str[-1]
df1['Experiment'] = e1.experiment_path.name
df2['Experiment'] = e2.experiment_path.name

# 2. Stack vertically and create the sorted MultiIndex
combined_df = pd.concat([df1, df2], axis=0)
multiview_df = combined_df.set_index(['File', 'Experiment']).sort_index()

exp1_name = e1.experiment_path.name
exp2_name = e2.experiment_path.name
exp1_temp = multiview_df.xs(exp1_name, level='Experiment')
exp2_temp = multiview_df.xs(exp2_name, level='Experiment')
exp1_temp, exp2_temp = exp1_temp.align(exp2_temp)

# # Find rows where at least one column differs
# changes_mask = (exp1_temp != exp2_temp) & ~(exp1_temp.isna() & exp2_temp.isna())
# changed_files = changes_mask.any(axis=1)

# # Overwrite multiview_df with the filtered version
# multiview_df = multiview_df.loc[changed_files.index[changed_files]]

# 3. Define the styling function for highlighting and borders
def style_multiview(df,exp1_name,exp2_name):
    # Create an empty DataFrame of the exact same shape to hold CSS strings
    styles = pd.DataFrame('', index=df.index, columns=df.columns)
    
    # Safely extract the two experiments
    exp1 = df.xs(exp1_name, level='Experiment')
    exp2 = df.xs(exp2_name, level='Experiment')
    
    # Align indices just in case a file is missing in one of the experiments
    exp1, exp2 = exp1.align(exp2)
    
    # Create a boolean mask of where the values differ
    diff_mask = (exp1 != exp2) & ~(exp1.isna() & exp2.isna())
    
    # Define our CSS rules
    border_css = 'border-bottom: 2px solid black; '
    highlight_css = 'background-color: #ffe5b4; color: #856404; '
    
    for col in df.columns:
        # A. Apply the black bottom border to ALL 'pretagging-flash-high' rows
        # This creates the visual separator between files
        exp2_rows = df.index[df.index.get_level_values('Experiment') == exp2_name]
        styles.loc[exp2_rows, col] = border_css
        
        # B. Find the specific files where this column changed
        changed_files = diff_mask.index[diff_mask[col]]
        
        # Map those files back to the MultiIndex tuple for the new experiment
        # (Filtering to ensure the file actually exists in the dataframe)
        idx_to_color = [(file, exp2_name) for file in changed_files if (file, exp2_name) in df.index]
        
        # Append the highlight CSS to the border CSS so we keep both!
        if idx_to_color:
            styles.loc[idx_to_color, col] += highlight_css
            
    return styles

# # 4. Apply the style
# multiview_df = multiview_df.sort_index(
#     level='File', 
#     key=lambda idx: idx.str.extract(r'^(\d+)', expand=False).astype(int)
# )
styled_df = multiview_df.style.apply(style_multiview, axis=None,**{"exp1_name": e1.experiment_path.name, "exp2_name": e2.experiment_path.name})
#styled_df = styled_df.hide(subset="Subspan,Superspan,Exact,Partial,IoU,Size,MultiMatch".split(","), axis="columns")
styled_df

In [ ]:
df.sum()

In [ ]:
e.evaluate_metrics()

# Correlation: Predictions and Fuzzy Matches

In [ ]:
e1 = Evaluator(
    Path.cwd() / "experiments" / "recall-pro-low-chunk2000".strip(),suffix="-lesser"
)
df = e1.evaluate_items()
df[df.Fuzzy != 0][["Prediction","Size","Fuzzy"]].corr("pearson")

            Prediction      Size     Fuzzy
Prediction    1.000000  0.558907  0.875796
Size          0.558907  1.000000  0.439000
Fuzzy         0.875796  0.439000  1.000000

# False Positives

In [ ]:
def getfps(glob):
    data = []
    for experiment in glob:
        try:
            data.extend(
                Evaluator(experiment).false_positives()
            )
        except ValueError as e:
            pass

    fps_by_doc = defaultdict(list)
    for doc_id, extraction in data:
        fps_by_doc[doc_id].append(extraction.extraction_text)

    # rapidfuzz scores from 0 to 100. 85.0 is a solid starting point for "fairly close"
    similarity_threshold = 85.0 
    clustered_results = []

    for doc_id, texts in fps_by_doc.items():
        clusters = [] 
        
        for text in texts:
            placed = False
            for cluster in clusters:
                # fuzz.ratio compares standard string similarity. 
                score = fuzz.ratio(text, cluster[0])
                
                if score >= similarity_threshold:
                    cluster.append(text)
                    placed = True
                    break
            
            if not placed:
                clusters.append([text])
                
        # 4. Compile the clusters into structured rows
        for cluster in clusters:
            clustered_results.append({
                "File": doc_id.split("/")[-1],
                "Representant": cluster[0],
                "Count": len(cluster),
                "Variants": cluster # Keeps all texts in case you need to inspect the differences
            })

    # 5. Convert to a DataFrame for analysis
    df_clusters = pd.DataFrame(clustered_results)

    # Sort by the most common false positives first
    return df_clusters.sort_values(by="Count", ascending=False).reset_index(drop=True)

def getfns(glob):
    data = []
    for experiment in glob:
        try:
            data.extend(
                Evaluator(experiment).false_negatives()
            )
        except ValueError as e:
            pass

    fps_by_doc = defaultdict(list)
    for doc_id, extraction in data:
        fps_by_doc[doc_id].append(extraction.extraction_text)

    # rapidfuzz scores from 0 to 100. 85.0 is a solid starting point for "fairly close"
    similarity_threshold = 85.0 
    clustered_results = []

    for doc_id, texts in fps_by_doc.items():
        clusters = [] 
        
        for text in texts:
            placed = False
            for cluster in clusters:
                # fuzz.ratio compares standard string similarity. 
                score = fuzz.ratio(text, cluster[0])
                
                if score >= similarity_threshold:
                    cluster.append(text)
                    placed = True
                    break
            
            if not placed:
                clusters.append([text])
                
        # 4. Compile the clusters into structured rows
        for cluster in clusters:
            clustered_results.append({
                "File": doc_id.split("/")[-1],
                "Representant": cluster[0],
                "Count": len(cluster),
                "Variants": cluster # Keeps all texts in case you need to inspect the differences
            })

    # 5. Convert to a DataFrame for analysis
    df_clusters = pd.DataFrame(clustered_results)

    # Sort by the most common false positives first
    return df_clusters.sort_values(by="Count", ascending=False).reset_index(drop=True)

In [ ]:
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', None)         # auto-detect display width
pd.set_option('display.max_rows', None)      # show

interesting = [
    # "pro-low-prompt_structure-addons-blended",
    # "pro-low-operational",
    "pro-low-base-persona-requirements-edge",
    "pro-low-base-persona-prescriptive-edge",
    # "pro-low-base",
    # "pro-low",
]

fps = getfps((Path.cwd() / "experiments"/"FINAL"/inter) for inter in  interesting)
# pro["Model"] = "pro"
# flash = getpfs((Path.cwd() / "experiments/recall").glob("recall-flash*"))
# flash["Model"] = "pro"
# fps = pd.concat([flash,pro])
# fps.sort_values("File")
fps[["File","Representant","Count"]]

,File,Representant,Count
0,responsible-use-autofix-code-scanning.md,After committing a suggested fix or modified f...,2
1,responsible-use-autofix-code-scanning.md,When you review a suggestion from Copilot Auto...,2
2,responsible-use-autofix-code-scanning.md,The best way to mitigate the limitations of su...,2
3,configuring-the-dependency-review-action.md,You can use the dependency review action to ca...,2
4,about-bypass-requests-for-push-protection.md,When push protection blocks a commit containin...,1
5,responsible-use-autofix-code-scanning.md,The system may suggest fixes that are not synt...,1
6,configuring-access-to-private-registries-for-d...,"For security reasons, Dependabot does not set ...",1
7,dependabot-errors.md,"If a security update times out, you can reduce...",1
8,dependabot-errors.md,"If a security update times out, you can reduce...",1
9,configuring-access-to-private-registries-for-d...,"For security reasons, Dependabot does not set ...",1
10,using-the-codeql-model-editor.md,Some methods support more than one data flow. ...,1
11,using-the-codeql-model-editor.md,Some methods support more than one data flow. ...,1
12,about-repository-security-advisories.md,You can create a security policy to give peopl...,1
13,configuring-the-dependency-review-action.md,Organization owners can roll out dependency re...,1
14,adding-a-security-policy-to-your-repository.md,You can give instructions for how to report a ...,1
15,use-artifact-attestations.md,You can also generate release attestations to ...,1
16,working-with-push-protection-in-the-github-ui.md,"When you upload, create, or edit files from th...",1
17,working-with-push-protection-in-the-github-ui.md,"To resolve a blocked commit in the web UI, you...",1

In [ ]:


interesting = [
    "pro-low-base-persona-requirements-edge",
    "pro-low-base-persona-prescriptive-edge",
    "pro-low-base-persona-requirements",
    "pro-low-base-persona-prescriptive",
    "pro-low-base-persona"
]

fps = getfps((Path.cwd() / "experiments"/"FINAL"/inter) for inter in  interesting)
# pro["Model"] = "pro"
# flash = getpfs((Path.cwd() / "experiments/recall").glob("recall-flash*"))
# flash["Model"] = "pro"
# fps = pd.concat([flash,pro])
# fps.sort_values("File")
fps

,File,Representant,Count,Variants
0,responsible-use-autofix-code-scanning.md,After committing a suggested fix or modified f...,5,[After committing a suggested fix or modified ...
1,responsible-use-autofix-code-scanning.md,When you review a suggestion from Copilot Auto...,5,[When you review a suggestion from Copilot Aut...
2,responsible-use-autofix-code-scanning.md,The best way to mitigate the limitations of su...,5,[The best way to mitigate the limitations of s...
3,about-repository-security-advisories.md,You can create a security policy to give peopl...,4,[You can create a security policy to give peop...
4,dependabot-errors.md,"If a security update times out, you can reduce...",4,"[If a security update times out, you can reduc..."
5,configuring-access-to-private-registries-for-d...,"For security reasons, Dependabot does not set ...",4,"[For security reasons, Dependabot does not set..."
6,configuring-the-dependency-review-action.md,You can use the dependency review action to ca...,4,[You can use the dependency review action to c...
7,working-with-push-protection-in-the-github-ui.md,"When you upload, create, or edit files from th...",4,"[When you upload, create, or edit files from t..."
8,working-with-push-protection-in-the-github-ui.md,"To resolve a blocked commit in the web UI, you...",4,"[To resolve a blocked commit in the web UI, yo..."
9,using-the-codeql-model-editor.md,Some methods support more than one data flow. ...,4,[Some methods support more than one data flow....
10,use-github-cli.md,"For each step that uses GitHub CLI, you must s...",3,"[For each step that uses GitHub CLI, you must ..."
11,enabling-delegated-bypass-for-push-protection.md,"Alternatively, you can grant specific organiza...",3,"[Alternatively, you can grant specific organiz..."
12,working-with-push-protection-in-the-github-ui.md,If you don't see the option to bypass the bloc...,3,[If you don't see the option to bypass the blo...
13,responsible-use-autofix-code-scanning.md,Copilot Autofix provides valuable information ...,2,[Copilot Autofix provides valuable information...
14,publish-in-github-marketplace.md,Publishing requires you to use two-factor auth...,2,[Publishing requires you to use two-factor aut...
15,about-bypass-requests-for-push-protection.md,When push protection blocks a commit containin...,2,[When push protection blocks a commit containi...
16,use-artifact-attestations.md,You can also generate release attestations to ...,2,[You can also generate release attestations to...
17,configuring-the-dependency-review-action.md,Organization owners can roll out dependency re...,2,[Organization owners can roll out dependency r...
18,adding-a-security-policy-to-your-repository.md,You can give instructions for how to report a ...,2,[You can give instructions for how to report a...
19,configuring-the-dependency-review-action.md,Organization owners can roll out dependency re...,2,[Organization owners can roll out dependency r...
20,configuring-access-to-private-registries-for-d...,"When using username and password, your `.npmrc...",2,"[When using username and password, your `.npmr..."
21,configuring-access-to-private-registries-for-d...,When you give Dependabot access to one or more...,2,[When you give Dependabot access to one or mor...
22,working-with-push-protection-in-the-github-ui.md,If your commit has been blocked by push protec...,2,[If your commit has been blocked by push prote...
23,write-security-advisories.md,The advisory curation team doesn't recommend s...,2,[The advisory curation team doesn't recommend ...
24,write-security-advisories.md,Although GitHub supports the use of the `>` op...,2,[Although GitHub supports the use of the `>` o...
25,working-with-push-protection-in-the-github-ui.md,If GitHub blocks a secret that you believe is ...,2,[If GitHub blocks a secret that you believe is...
26,responsible-use-autofix-code-scanning.md,The system may suggest fixes that are not synt...,1,[The system may suggest fixes that are not syn...
27,configuring-access-to-private-registries-for-d...,To give Dependabot access to the private regis...,1,[To give Dependabot access to the private regi...
28,dependabot-errors.md,"If a security update times out, you can reduce...",1,"[If a security update times out, you can reduc..."
29,dependabot-errors.md,If a grouped pull request for security updates...,1,[If a grouped pull request for security update...
30,using-the-codeql-model-editor.md,Some methods support more than one data flow. ...,1,[Some methods support more than one data flow....
31,configuring-access-to-private-registries-for-d...,"For security reasons, Dependabot does not set ...",1,"[For security reasons, Dependabot does not set..."
32,configuring-dependabot-alerts.md,"By default, we notify people with write, maint...",1,"[By default, we notify people with write, main..."
33,use-artifact-attestations.md,To keep your attestations relevant and managea...,1,[To keep your attestations relevant and manage...
34,configuring-dependabot-alerts.md,"Additionally, you can use Dependabot auto-tria...",1,"[Additionally, you can use Dependabot auto-tri..."
35,planning-a-trial-of-ghas.md,Organizations on GitHub Team and GitHub Enterp...,1,[Organizations on GitHub Team and GitHub Enter...
36,managing-custom-patterns.md,Before enabling push protection for a custom p...,1,[Before enabling push protection for a custom ...
37,managing-custom-patterns.md,Before enabling push protection for a custom p...,1,[Before enabling push protection for a custom ...

In [ ]:
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.width', 1)         # auto-detect display width
pd.set_option('display.max_rows', None)      # show